json.user @order.user
json.product @order.product
json.product_pictures @order.product.pictures
json.quantity @order.quantity
json.subtotal @order.subtotal
json.tax @order.tax
json.total @order.total
json.created_at @order.created_at
json.updated_at @order.updated_at